services:
  - type: web
    name: tnv-django
    env: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn tnv.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: tnv-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ".onrender.com"